### ISSUE TITLE
Is Flexify the future?

### ISSUE THREAD

**Issue by nearapogee** [brandonp2412/Massive#1]
I have been using Massive for some time now. But it looks like Flexify is getting more commits.

Thank you for your apps!

**Comment by brandonp2412** [comment]
I'm mainly adding features to Flexify but its a separate project to this.

The biggest difference between the two is the framework used, Flutter vs React Native.

I'll continue to fix bugs and push package updates every now and then but I'm mainly working on my flutter apps.
