### ISSUE TITLE
Exercise names which have commas get separated into multiples (Version 2.36 F-Droid)

### ISSUE THREAD

**Issue by schki** [brandonp2412/Massive#3]
After creating an exercise with more details in the title, e.g.:
"Bench Press (Dumbbell, Underhand Grip)"
The exercise gets split in two when putting togehter the plan:
(on/off slider) "Bench Press (Dumbbell"
(on/off slider) "Underhand Grip"

Of course you can get around it by avoiding commas in the exercise name (like "Dumbbell Bench Press (Underhand Grip)"), but it's still annoying when I forget about it.

**Comment by brandonp2412** [comment]
This would require a large re-work of the code base which I won't be doing. I mainly add and change large things on https://github.com/brandonp2412/Flexify. Massive I make bug fixes and small updates
